language: r
warnings_are_errors: true
cache: packages

r:
  - oldrel
  - release
  - devel
  
r_binary_packages:
  - nlme
  - stringi
  - scales
  - ggplot2
  - Hmisc
  - rms

notifications:
  email:
    recipients:
        - work@wrig.de
    on_success: change
    on_failure: change
    