// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// weighted_kaplan_meier
Rcpp::NumericVector weighted_kaplan_meier(Rcpp::NumericMatrix response, Rcpp::NumericVector weights, Rcpp::NumericVector timepoints);
RcppExport SEXP bnnSurvival_weighted_kaplan_meier(SEXP responseSEXP, SEXP weightsSEXP, SEXP timepointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type response(responseSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type timepoints(timepointsSEXP);
    __result = Rcpp::wrap(weighted_kaplan_meier(response, weights, timepoints));
    return __result;
END_RCPP
}
